### ISSUE TITLE
Rename the crate

### ISSUE THREAD

**Issue by asajeffrey** [asajeffrey/josephine#19]
Linjs is a pretty poor name. Oh bikeshedding, how I love you!

**Comment by fitzgen** [comment]
* `borrowjs`
* `bojs`
* `bjs`
* `beauxjs`
* `ajjs`
* `jay_ess`
* `green`
* `bikeshedjs`
* `rsjs`
* `jsrs`

**Comment by asajeffrey** [comment]
* safejs
* jsmanaged
* rustymonkey

**Comment by asajeffrey** [comment]
I like `bojs` (or `beauxjs` or `beaujs`) for the pun with https://en.wikipedia.org/wiki/Beau_Geste. @nox: does this pass the baguette test?

**Comment by jdm** [comment]
`a-fine-js`

**Comment by asajeffrey** [comment]
Oh more puns https://en.wikipedia.org/wiki/Another_Fine_Mess

Slightly annoyingly https://en.wikipedia.org/wiki/A_Fine_Mess_(film)

**Comment by nox** [comment]
AFineMonkey.

**Comment by nox** [comment]
Why say `js` when you could say `monkey`?

**Comment by nox** [comment]
OK OK, I found the perfect name.

Josephine. Or Josefine.

**Comment by asajeffrey** [comment]
@nox has a winner!

IRC conversation: https://mozilla.logbot.info/servo/20171021#c13731468

**Comment by asajeffrey** [comment]
Closed by https://github.com/asajeffrey/josephine/commit/658a898bc07fb436fa9c6c55d37ca46e7551670c
