### ISSUE TITLE
Safe rooting, even with `mem::forget`

### ISSUE THREAD

**Issue by asajeffrey** [asajeffrey/josephine#21]
@nox on IRC (http://logs.glob.uno/?c=mozilla%23servo&s=1+Oct+2017&e=1+Oct+2017#c761560) pointed out that @Sgeo gave a way (https://play.rust-lang.org/?gist=349d6cd20c456b22d750bd6d405f2d7f&version=stable) to implement immovable data in Rust, which should make the rooting API safe even in the presence of `mem::forget`.

**Comment by fitzgen** [comment]
That still requires two steps (with no way to abstract them into an atomic step besides macros) though:

1. create
2. immobilize

which is essentially what `rooted!` is doing as well.

**Comment by fitzgen** [comment]
We need real lang support for immovable types yesterday ;)

**Comment by nox** [comment]
@fitzgen These two steps can be done in safe code right now, without a lint, and we know for sure the thing won't move. But in other news, [this](https://github.com/rust-lang/rust/pull/44917) happened.

**Comment by asajeffrey** [comment]
Yes, the code would still be something like:
```rust
   let root = cx.new_root();
   let pinned = root.pin(thing);
```
the advantage of immovable types is that we could combine these by pinning the root during its constructor. I'd still rather have two lines of code than the `rooted!` macro, but we're into issues of taste  now.

**Comment by fitzgen** [comment]
> @fitzgen These two steps can be done in safe code right now, without a lint, and we know for sure the thing won't move.

If they are two different steps, what stops someone from forgetting (or not knowing) to do them back to back and inserting a call to something that can GC between the two steps?

I would want a lint to protect against that.

> But in other news, this happened.

Yes, I am awaiting excitedly :)

**Comment by asajeffrey** [comment]
That won't typecheck, since the JS-managed thing has to be live at the point you pin it.

**Comment by fitzgen** [comment]
D'oh, that's right. Ok!

**Comment by asajeffrey** [comment]
Ah, modifying @Sgeo's code to impl Drop causes it not to compile: https://play.rust-lang.org/?gist=3af363af5b800dc0e874c1f07bc10b7f&version=stable

IRC chat: https://botbot.me/mozilla/rust/2017-10-12/?msg=92239007&page=20

**Comment by asajeffrey** [comment]
I keep forgetting about `#[may_dangle]`. Perhaps I should get it tatooed. https://play.rust-lang.org/?gist=4544e6f0aa35abb10b02d7ece1787c34&version=nightly

**Comment by asajeffrey** [comment]
Fixed in https://github.com/asajeffrey/linjs/commit/814bc2d201dedbf0bea36f3aa75924df0def5674
