### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by asajeffrey** [asajeffrey/josephine#35]
The problem is that `rust-mozjs` isn't published, so we end up with:
```
$ cargo publish
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: crates cannot be published to crates.io with dependencies sourced from a repository
either publish `js` as its own crate on crates.io and specify a crates.io version as a dependency or pull it into this repository and specify it with a path and version
(crate `js` has repository path `https://github.com/servo/rust-mozjs`)
```
cc @fitzgen

**Comment by fitzgen** [comment]
What @tschneidereit and I talked about was publishing to crates.io with `0.X.0` versions where `X` is the current m-c we are publishing from. Frequency of publishing was just whenever we needed it, but I could imagine a further future where it automatically happened with m-c releases.

I remember @nox had concerns about semver compatibility.

The reality is that every release is potentially a breaking change, and it is mostly out of our hands.

**Comment by asajeffrey** [comment]
@fitzgen that sounds sensible. Do you know what the timeline on this would be? I'd like to announce josephine soonish, and publishing on crates.io is a blocker.

**Comment by fitzgen** [comment]
We could do it now if you don't care about windows.

**Comment by asajeffrey** [comment]
Yes please!

**Comment by nox** [comment]
If all releases will contain breaking changes, or if the whole crate is automatically generated and thus  we aren't sure about the scope of the changes, we should do only `0.x.0` releases, or maybe even  `0.0.x`.

@fitzgen What do you mean by "the current m-c we are publishing from"?

**Comment by asajeffrey** [comment]
We could do 0.0.YYYYMMDD while we're working out a more sensible versioning scheme?

**Comment by nox** [comment]
@asajeffrey An ever increasing number means we can just still +1 when we switch to something else but still at the same 0.0 level, and that we don't have to ask ourselves what to do if we do 2 releases on the same day.

IMO `0.0.x` gives as many guarantees as it sounds, in this case none, which is nice.

**Comment by asajeffrey** [comment]
Yes, 0.0.x is at least honest.

**Comment by asajeffrey** [comment]
@fitzgen reminded me today about https://crates.io/crates/js which means the mozjs crate name should probably be `mozjs` rather than `js`.

**Comment by jdm** [comment]
Or even spidermonkey.

**Comment by asajeffrey** [comment]
As a stopgap until mozjs is released, I can probably vendor it into my local copy of the repo, put the local copy in the .gititnore to stop it getting checked in, then publish josephine on crates.io.

**Comment by asajeffrey** [comment]
Oh rats, vendoring isn't as simple as I'd hoped, it looks like that error message led me up the garden path.

IRC chat with @mbrubeck: https://botbot.me/mozilla/rust/2017-10-31/?msg=92958778&page=16

**Comment by asajeffrey** [comment]
Mozjs is now on crates.io, and so is Josephine! https://crates.io/crates/josephine
