### ISSUE TITLE
Bikeshedding trait names

### ISSUE THREAD

**Issue by asajeffrey** [asajeffrey/josephine#37]
The four traits for user defined data should be renamed. I am thinking:
```
JSRootable       -> JSManagedLifetime
JSTransplantable -> JSManagedCompartment
JSInitializable  -> JSManagedObject
```
`JSTraceable` can stay the same.

**Comment by fitzgen** [comment]
In general, `JsBlah` is more common than `JSBlah` as a convention for acronyms in identifiers. The `js` crate is p bad at this right now.

**Comment by asajeffrey** [comment]
Oh pox, I have to decide whose naming convention to follow? I am tempted to try to drop the `JS` totally to avoid this :/ The only one that's very JS specific is `JSInitializable` which links against jsapi types like `JSClass`.

**Comment by asajeffrey** [comment]
Closed by https://github.com/asajeffrey/josephine/commit/a8acacbbece6cd75ea87e63158b9fba64e0e172a and https://github.com/asajeffrey/josephine/commit/bb422ea1d5d8ea885491e95213f7a018562be917.
