### ISSUE TITLE
Enable dependency caching on travis

### ISSUE THREAD

**Issue by asajeffrey** [asajeffrey/josephine#46]
At the moment, ccache is running during builds of josephine, to cache previous builds of `mozjs_sys`, but it's not having any effect, e.g. https://travis-ci.org/asajeffrey/josephine/builds/299995511#L1729
```
$ ccache -s
cache directory                     /home/travis/.ccache
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                           518
called for link                        2
called for preprocessing              10
compile failed                         5
preprocessor error                    19
unsupported source language            1
autoconf compile/link                 51
unsupported compiler option            1
no input file                          5
files in cache                       880
cache size                         331.4 Mbytes
max cache size                     512.0 Mbytes
```

**Comment by asajeffrey** [comment]
@nox filed https://github.com/travis-ci/travis-ci/issues/8753

**Comment by nox** [comment]
We could probably do just like in https://github.com/servo/gecko-media/pull/43.

**Comment by asajeffrey** [comment]
Ah, now that mozjs is on crates.io, perhaps we can just switch to `cache: cargo`?

**Comment by asajeffrey** [comment]
Trying out cargo caching... https://github.com/asajeffrey/josephine/commit/b606ab3f292cac28e197fa39906b488b89356847

**Comment by asajeffrey** [comment]
Grr... https://travis-ci.org/asajeffrey/josephine/jobs/301577936#L441

**Comment by asajeffrey** [comment]
Yay, it's working now, build times are down from 15mins to 5mins.

@nox points out on IRC that when mozjs_sys gets updated, it's going to do a full rebuild, but hopefully that won't be too painful. https://mozilla.logbot.info/servo/20171114#c13846533
